kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: my-cluster
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080   # NodePort
        hostPort: 80           # EC2 public port
        protocol: TCP
  - role: worker
  - role: worker
